config/routes.rb
Rails.application.routes.draw do
 resources :cars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.order (:year )
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)

    if @car.save
      redirect_to car_path(@car.id)
    else
      render :new
    end

  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])

    if @car.update(car_params)
      redirect_to car_path
    else
      render :edit
    end

  end

  def destroy
    Car.find(params[:id]).destroy
    redirect_to cars_path
  end



  private
  def car_params
    params.require(:car).permit(:make, :model, :year, :color, :msrp, :used)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for @car do |f| %>
  <%= f.label :make %>
    <%= f.text_field :make %>

    <%= f.label :model %>
    <%= f.text_field :model %>

    <%= f.label :year %>
    <%= f.text_field :year %>

    <%= f.label :color %>
    <%= f.text_field :color %>

    <%= f.label :msrp %>
    <%= f.text_field :msrp %>

    <%= f.label :used %>
    <%# <%= f.text_field :used %>
    <%= f.select(:used, options_for_select([['True', true], ['False', false]], @car.used))%>

    <%= f.submit %>
  <% end %>

app/views/cars/edit.html.erb
<h1>Edit Car</h1>
<%= render 'form' %>

app/views/cars/index.html.erb
<div>
<h3>Car List</h3>
  <table>
    <tr>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      <th>Color</th>
      <th>MSRP</th>
      <th>Used</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.make %></td>
        <td><%= car.model %></td>
        <td><%= car.year %></td>
        <td><%= car.color %></td>
        <td>$<%= car.msrp %></td>
        <td><%= car.used %></td>
        <td><%= link_to 'Show', car_path(car.id) %></td>
        <td><%= link_to 'Edit', edit_car_path(car.id) %></td>
        <td><%= link_to 'Delete', car_path(car.id), method: :delete %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/cars/new.html.erb
<h1>Add New Car</h1>
<%= render 'form' %>

app/views/cars/show.html.erb
<h1>Cars Info</h1>
<%= @car.makes %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', cars_path %>
<%= link_to 'Add Car', new_car_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dealership</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>